// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeznsmyshhrgcqkhgtmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlem5zbXlzaGhyZ2Nxa2hndG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDQyMjcsImV4cCI6MjA3NDAyMDIyN30.ZgDBA56TDMOd8zzSLWBDEtg5knyEUMLaC2JHe4Z0Tx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});